export const products = [
  {
    id: "SKUCO40101001",
    name: "Monitor ",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/monitor.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 28,
    seq: 33,
    info: null,
    weight: 8390,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "52",
    default_unit_id: 2,
    color_code: "#CBF0E1",
    quality_req: null,
  },
  {
    id: "SKUCO40101002",
    name: "CPU/Server",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/cpu.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 78,
    seq: 34,
    info: null,
    weight: 8390,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "53",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101003",
    name: "Laptops",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/laptop.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 59,
    seq: 31,
    info: null,
    weight: 2410,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "60",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101004",
    name: "Printer/Scanner/Fax",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/printer.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 49,
    seq: 36,
    info: null,
    weight: 34100,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "62",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101005",
    name: "UPS",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/ups.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 57,
    seq: 35,
    info: null,
    weight: 1900,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "63",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101006",
    name: "Mobile Phone - Feature Phone",
    icon:
      "https://uzed.s3.amazonaws.com/recykal/icons/items/mobile_feature_phone.jpg",
    category_id: "CO40101",
    is_active: false,
    price: 67,
    seq: 30,
    info: null,
    weight: 170,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "237",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101007",
    name: "Mobile Phone - Smartphone",
    icon:
      "https://uzed.s3.amazonaws.com/recykal/icons/items/mobile_smartphone.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 26,
    seq: 29,
    info: null,
    weight: 170,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "238",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101008",
    name: "Tablet",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/tablet.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 45,
    seq: 47,
    info: null,
    weight: 1050,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "243",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101009",
    name: "Desktop",
    icon: "https://uzed.s3.amazonaws.com/recykal/icons/items/desktop.jpg",
    category_id: "CO40101",
    is_active: false,
    price: 24,
    seq: 32,
    info: null,
    weight: 8390,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "247",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
  {
    id: "SKUCO40101010",
    name: "External Hard Drive",
    icon:
      "https://uzed.s3.amazonaws.com/recykal/icons/items/external_hard_drive.jpg",
    category_id: "CO40101",
    is_active: true,
    price: 120,
    seq: 37,
    info: null,
    weight: 270,
    cgst_percentage: 2.5,
    hsn: "4707",
    sgst_percentage: 2.5,
    number_of_buyers: 4,
    modified_at: "2019-10-11 13:01:23",
    description: "",
    is_exchange_catalog: false,
    is_non_exchange_catalog: true,
    old_id: "251",
    default_unit_id: 2,
    color_code: null,
    quality_req: null,
  },
];
